language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "tacolife-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: tacolife # see README
  api_key:
    secure: "D6BTFtqNkSqP2wF70VcQrKImCf7CViQ9bLIK/RZIFfb3jpJCRbiNcw6GZyD2VjYItl1bEBfjTkzkeL1QsP7Nq5ghpY1CQiYuIq88Qav3FTC2HCbb2SDhX3nqphLN+6WKvaezPS+fRHrWiRUyP1MYiVAsGYt0FzIVd16HDoiIsGRpUWe2Dc4jLi4fJ2ECgA9EzGtiL8HbYSX+ZMLKoC7qVjqCXNXjB1iqEow4/aQIJ3ZqhaGbpBtQTAiCdxmbNipfAvmjOrV14m/bIYC5BhXn2PGOdCPoIV2+jquJsyT+ahDFmzSXEhXpxFd0rMxUddJ0H11Vf1EV9+KKVthcCJSIomEeZJ0ZM/yCVqa4HgYia/mkoZMuGDpsmZyQj/yr4jCS8Qer2czswhQ2j8zXRsgA5M/drlvd1T3Qf94b+dxc1hSZr41KUXoYvQIBbxVAcOW5kMvFyHGnhw8NhfXFW+115EuZsGd0Ath0HfK36ncXoVnbafbTSKhWy/SaZOp/uQUwRFKZIG11NZy2wIweS/+x79O0crISfXxVBysasYPSHxMWZJ+tDx5l3cYtDT9dUW5Y4sHPmSdnAHWc16SnV3Oir7XcUBw2D7TUShAoVHKFCekA86FzUtaxFsq5+9dkmYoIRkRHOu/u1sTK3b3iw/8+nc6BImHX/g7szQmN+NQPh5g="
